[package]
name = "rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
druid = "0.8.3"
druid-shell = "0.8.3"
rand = "0.8.5"
random = "0.14.0"
