[package]
name = "rust_hex"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }


[[bench]]
name = "evaluations"
harness = false

[[bench]]
name = "best_list"
harness = false